#!/bin/sh
echo "Start running pacman_init script ...";
sudo pacman-mirros -i -c China -m rank &&
echo "Selected fastest mirrors." ;
sudo echo "[archlinuxcn]" >> /etc/pacman.conf &&
sudo echo "SigLevel = Optional TrustAll" >> /etc/pacman.conf &&
sudo echo "Server = https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/$arch" >> /etc/pacman.conf &&
echo "added archlinuxcn_tuna to /etc/pacman.conf ";
sudo sed -i "1iServer = https://mirrors.scau.edu.cn/archlinux/\$repo/os/\$arch" /etc/pacman.d/mirrorlist &&
echo "added SCAU mirrors(archlinuxcn) to mirrorlist.";
echo "updating database...";
sudo pacman -Syy &&
echo "installing archlinuxcn-keyring and yaourt ...";
sudo pacman -S --noconfirm archlinuxcn-keyring yaourt &&
sudo mkdir /opt/pamac-build/ && sudo chmod 777  /opt/pamac-build/;
echo "exiting pacman_init script ...";
