#!/bin/sh
echo "installing sogoupinyin ...";
sudo pacman -S --noconfirm qtwebkit-bin &&
sudo pacman -S --noconfirm fcitx-gtk3 fcitx-qt4 fcitx-qt5 fcitx-sogoupinyin &&
echo "setuping sogoupinyin ...";
echo "export LC_ALL=zh_CN.UTF-8" >> ~/.xprofile
echo "export GTK_IM_MODULE=fcitx" >> ~/.xprofile
echo "export QT_IM_MODULE=fcitx" >> ~/.xprofile
echo "export XMODIFIERS=@im=fcitx" >> ~/.xprofile

echo "done. exiting sogoupinyin script...";
