#!/bin/bash

fun(){
    time=`cat /sys/class/rtc/rtc0/time`
    time=${time:0:2}
    time=$((10#${time}))
    t=6

    if [ $time -lt $t ]
    then
	    echo "the hour is $time, continue sleeping..."
	    sleep 15m
	    fun
    else
	    echo "time:$time"
	    sudo /opt/ruijie/ruijie &&
	    sudo /opt/ruijie/AP
    fi
}

check() {
    #检测网络连接
    ping -c 1 114.114.114.114 > /dev/null 2>&1
    if [ $? -eq 0 ];then
		echo 检测网络正常
		sleep 1m
		check
    else
		echo 检测网络连接异常
		fun
		check
    fi
}
sudo echo 
check
echo "exited."
