#!/bin/sh

if [ ! -d /tmp/check_ruijie ]; then
	mkdir /tmp/check_ruijie
	echo 
fi

cd /tmp/check_ruijie

if [ -f *.pid ]; then
	pid=`ls *.pid`
	pid=${pid%.*}
	sudo kill $pid
	rm *.pid
fi


sudo nohup /opt/ruijie/__check_ruijie > /tmp/check_ruijie.log 2>&1 &
touch $!".pid"

cd -
