#!/bin/sh
sed -i '/_id_passwd/d' /etc/profile
sudo rm /etc/systemd/system/AP.service
sudo rm /etc/systemd/system/ruijie.service
sudo rm /etc/systemd/system/check_ruijie.service
sudo rm -r /opt/ruijie

